export { ConfirmationDesktop as Confirmation } from './component.desktop.js';
export { ConfirmationResponsive } from './component.responsive.js';
export { Initial } from './components/screens/initial/component.js';
export { Hint } from './components/screens/hint/component.js';
export { FatalError } from './components/screens/fatal-error/component.js';
export { TempBlock } from './components/screens/temp-block/component.js';
export { CountdownLoader } from './components/countdown-loader/component.js';
export { ConfirmationContext } from './context.js';
export { defaultTexts } from './types.js';
export { ONE_DAY, ONE_MINUTE, formatMsAsMinutes, useConfirmation, useCountdown } from './utils.js';
import 'react';
import './components/base-confirmation/component.js';
import 'classnames';
import '@alfalab/hooks';
import '../../button/modern';
import '../../code-input/modern';
import '../../link/modern';
import '../../typography/modern';
import './components/header/component.js';
import './countdown-section-e6fd8508.js';
import '../../loader/modern';
import './component.mobile.js';
