declare const DATE_FORMAT = "dd.MM.yyyy";
declare const DATE_MASK: (string | RegExp)[];
declare const DATE_WITH_TIME_LENGTH: number;
declare const isCompleteDateInput: (input: string) => boolean;
declare const parseDateString: (value: string, dateFormat?: string) => Date;
declare const isValidTimeFormat: (value: string) => boolean;
declare const isValid: (inputValue: string) => boolean;
declare const format: (value: string) => string;
declare const parseTimestampToDate: (timestamp: number) => string;
declare const getDateWithoutTime: (value: string) => Date;
declare const getFullDateTime: (value: string) => Date;
declare const addTimeToDate: (value: string) => string;
export { DATE_FORMAT, DATE_MASK, DATE_WITH_TIME_LENGTH, isCompleteDateInput, parseDateString, isValidTimeFormat, isValid, format, parseTimestampToDate, getDateWithoutTime, getFullDateTime, addTimeToDate };
