export { CountriesSelect } from './component.js';
import '../../component-064f33de.js';
import 'react';
import 'react-merge-refs';
import 'classnames';
import '@alfalab/hooks';
import '@alfalab/icons-glyph/WorldMagnifierMIcon';
import '../flag-icon/component.js';
import '../../../../select/esm';
import '../flag-icon/flagSprite.js';
