export { CalendarInputMobile } from './Component.mobile.js';
import 'react';
import '../../calendar/modern';
import './components/calendar-input/Component.js';
import 'react-merge-refs';
import 'classnames';
import '../../date-input/modern';
import '../../popover/modern';
import '@alfalab/icons-glyph/CalendarMIcon';
import './utils.js';
import 'date-fns/format';
import 'date-fns/isSameDay';
import 'date-fns/parse';
