var Component = require('./Component.js');
var utils_splitFilename = require('./utils/split-filename.js');
var utils_utils = require('./utils/utils.js');
var utils_constants = require('./utils/constants.js');
require('react');
require('../base-modal');
require('./components/navigation-bar/Component.js');
require('./context.js');
require('./components/image-preview/Component.js');
require('classnames');
require('@alfalab/hooks');
require('./components/image-preview/paths.js');
require('./components/header/Component.js');
require('./components/header-info-block/Component.js');
require('../typography');
require('./components/header/buttons.js');
require('./tslib.es6-2f64e669.js');
require('../icon-button');
require('../tooltip');
require('@alfalab/icons-glyph/ArrowsInwardMIcon');
require('@alfalab/icons-glyph/ArrowsOutwardMIcon');
require('@alfalab/icons-glyph/CrossMIcon');
require('@alfalab/icons-glyph/PointerDownMIcon');
require('./components/image-viewer/component.js');
require('element-closest');
require('swiper');
require('swiper/react');
require('@alfalab/icons-glyph/ChevronBackHeavyMIcon');
require('@alfalab/icons-glyph/ChevronForwardHeavyMIcon');
require('./slide-4d2aff75.js');
require('./components/image-viewer/paths.js');
require('swiper/swiper.min.css');



exports.Gallery = Component.Gallery;
exports.splitFilename = utils_splitFilename.splitFilename;
exports.PLACEHOLDER_HEIGHT = utils_utils.PLACEHOLDER_HEIGHT;
exports.PLACEHOLDER_WIDTH = utils_utils.PLACEHOLDER_WIDTH;
exports.getImageAlt = utils_utils.getImageAlt;
exports.getImageKey = utils_utils.getImageKey;
exports.isSmallImage = utils_utils.isSmallImage;
exports.TestIds = utils_constants.TestIds;
