export { Attach } from './Component.js';
import 'react';
import 'react-merge-refs';
import 'classnames';
import '../../button/esm';
import '../../keyboard-focusable/esm';
import '../../progress-bar/esm';
import '@alfalab/icons-glyph/PaperclipMIcon';
import '@alfalab/icons-glyph/PaperclipSIcon';
import '@alfalab/utils';
import './utils/index.js';
