export { Steps } from './Component.js';
import 'react';
import 'classnames';
import './components/step/Component.js';
import '@alfalab/hooks';
import '@alfalab/icons-glyph/CheckmarkCircleMIcon';
import '@alfalab/icons-glyph/ClockMIcon';
import '@alfalab/icons-glyph/ExclamationCircleMIcon';
import './components/step-indicator/Component.js';
import '../../badge/esm';
