export { Gallery } from './Component.js';
export { splitFilename } from './utils/split-filename.js';
export { PLACEHOLDER_HEIGHT, PLACEHOLDER_WIDTH, getImageAlt, getImageKey, isSmallImage } from './utils/utils.js';
export { TestIds } from './utils/constants.js';
import 'react';
import '../../base-modal/modern';
import './components/navigation-bar/Component.js';
import './context.js';
import './components/image-preview/Component.js';
import 'classnames';
import '@alfalab/hooks';
import './components/header/Component.js';
import './components/header-info-block/Component.js';
import '../../typography/modern';
import '../../icon-button/modern';
import '../../tooltip/modern';
import '@alfalab/icons-glyph/ArrowsInwardMIcon';
import '@alfalab/icons-glyph/ArrowsOutwardMIcon';
import '@alfalab/icons-glyph/CrossMIcon';
import '@alfalab/icons-glyph/PointerDownMIcon';
import './components/image-viewer/component.js';
import 'element-closest';
import 'swiper';
import 'swiper/react';
import '@alfalab/icons-glyph/ChevronBackHeavyMIcon';
import '@alfalab/icons-glyph/ChevronForwardHeavyMIcon';
import './slide-d07efafa.js';
import 'swiper/swiper.min.css';
import './components/header/buttons.js';
import './components/image-preview/paths.js';
import './components/image-viewer/paths.js';
