export { SidePanelResponsive } from './Component.responsive.js';
export { ModalContext } from './Context.js';
import 'react';
import '@alfalab/hooks';
import './components/closer/Component.js';
import 'classnames';
import '../../icon-button/esm';
import '../../base-modal/esm';
import './Component.desktop.js';
import 'react-merge-refs';
import '../../drawer/esm';
import './components/content/Component.desktop.js';
import './components/content/Component.js';
import './components/footer/Component.desktop.js';
import './components/footer/Component.js';
import './components/header/Component.desktop.js';
import '@alfalab/icons-glyph/CrossHeavyMIcon';
import './components/header/Component.js';
import './Component.mobile.js';
import './components/content/Component.mobile.js';
import './components/footer/Component.mobile.js';
import './components/header/Component.mobile.js';
import '@alfalab/icons-glyph/CrossMIcon';
import './tslib.es6-46a2fd0f.js';
