export { SelectWithTags } from './component.js';
import 'react';
import '../../select/esm';
import './components/tag-list/component.js';
import 'classnames';
import '../../form-control/esm';
import '@alfalab/hooks';
import './components/tag/component.js';
import '../../tag/esm';
import '@alfalab/icons-glyph/CrossCompactMIcon';
import './tslib.es6-411b8c4a.js';
import './utils/match.js';
import './utils/calculate-collapse-size.js';
