export { B as BottomSheet, C as CLOSE_OFFSET, H as HEADER_OFFSET } from './component-d2ec1278.js';
import 'react';
import 'react-div-100vh';
import 'react-swipeable';
import 'classnames';
import '../../base-modal/modern';
import './components/footer/Component.js';
import '../../typography/modern';
import '../../backdrop/modern';
import './components/backer/Component.js';
import '../../icon-button/modern';
import '@alfalab/icons-glyph/ArrowBackMIcon';
import './components/closer/Component.js';
import '@alfalab/icons-glyph/CrossMIcon';
import './components/swipeable-backdrop/Component.js';
