import 'react';
import 'react-div-100vh';
import 'react-swipeable';
import 'classnames';
import '../../base-modal/esm';
export { B as BottomSheet, C as CLOSE_OFFSET, H as HEADER_OFFSET } from './component-efdd9be5.js';
import './components/footer/Component.js';
import '../../backdrop/esm';
import '../../typography/esm';
import './components/backer/Component.js';
import '../../icon-button/esm';
import '@alfalab/icons-glyph/ArrowBackMIcon';
import './components/closer/Component.js';
import '@alfalab/icons-glyph/CrossMIcon';
import './tslib.es6-1d201b00.js';
import './components/swipeable-backdrop/Component.js';
