export { Initial } from './screens/initial/component.js';
export { Hint } from './screens/hint/component.js';
export { FatalError } from './screens/fatal-error/component.js';
export { TempBlock } from './screens/temp-block/component.js';
export { CountdownLoader } from './countdown-loader/component.js';
import 'react';
import 'classnames';
import '../../../button/modern';
import '../../../code-input/modern';
import '../../../link/modern';
import '../../../typography/modern';
import '@alfalab/hooks';
import '../context.js';
import './header/component.js';
import '../countdown-section-e6fd8508.js';
import '../../../loader/modern';
import '../utils.js';
