export { FileUploadItem } from './Component.js';
import 'react';
import 'classnames';
import '../../icon-button/modern';
import '../../link/modern';
import '../../spinner/modern';
import '@alfalab/icons-glyph/AlertCircleMIcon';
import '@alfalab/icons-glyph/CheckmarkCircleMIcon';
import '@alfalab/icons-glyph/ClockMIcon';
import '@alfalab/icons-glyph/CrossSIcon';
import '@alfalab/icons-glyph/PointerDownSIcon';
import '@alfalab/icons-glyph/DocumentDocMIcon';
import '@alfalab/icons-glyph/DocumentImageMIcon';
import '@alfalab/icons-glyph/DocumentPdfMIcon';
import '@alfalab/icons-glyph/DocumentTxtMIcon';
import '@alfalab/icons-glyph/DocumentUnknownMIcon';
import './utils.js';
