export { DateRangeInputDesktop } from './Component.desktop.js';
import './Component-6b915ca3.js';
import 'react';
import 'react-merge-refs';
import 'classnames';
import 'date-fns/isValid';
import '../../calendar/esm';
import '../../icon-button/esm';
import '../../input/esm';
import '../../popover/esm';
import '@alfalab/hooks';
import '@alfalab/icons-glyph/CalendarMIcon';
import 'date-fns/parse';
import './utils/format.js';
