export { Initial } from './initial/component.js';
export { Hint } from './hint/component.js';
export { FatalError } from './fatal-error/component.js';
export { TempBlock } from './temp-block/component.js';
import 'react';
import 'classnames';
import '../../../../button/esm';
import '../../../../code-input/esm';
import '../../../../link/esm';
import '../../../../typography/esm';
import '@alfalab/hooks';
import '../../context.js';
import '../header/component.js';
import '../../countdown-section-8814b585.js';
import '../../../../loader/esm';
import '../countdown-loader/component.js';
import '../../utils.js';
