export { Typography } from './component.js';
export { typographyPresets } from './presets.js';
import './text/component.js';
import 'react';
import 'classnames';
import './colors.module-bcb26f1f.js';
import './title/index.js';
import './title/component.js';
import './common.module-0f62e833.js';
import './title-mobile/component.js';
import './title-responsive/component.js';
