var Component_responsive = require('./Component.responsive.js');
var Context = require('./Context.js');
require('./tslib.es6-bbd6cd2a.js');
require('react');
require('@alfalab/hooks');
require('./components/closer/Component.js');
require('classnames');
require('../../icon-button/cssm');
require('./components/closer/index.module.css');
require('../../base-modal/cssm');
require('./Component.desktop.js');
require('react-merge-refs');
require('../../drawer/cssm');
require('./components/content/Component.desktop.js');
require('./components/content/Component.js');
require('./components/content/index.module.css');
require('./components/content/desktop.module.css');
require('./components/footer/Component.desktop.js');
require('./components/footer/Component.js');
require('./components/footer/index.module.css');
require('./components/footer/layout.module.css');
require('./components/footer/desktop.module.css');
require('./components/header/Component.desktop.js');
require('@alfalab/icons-glyph/CrossHeavyMIcon');
require('./components/header/Component.js');
require('./components/header/index.module.css');
require('./components/header/desktop.module.css');
require('./desktop.module.css');
require('./transitions.desktop.module.css');
require('./Component.mobile.js');
require('./components/content/Component.mobile.js');
require('./components/content/mobile.module.css');
require('./components/footer/Component.mobile.js');
require('./components/footer/mobile.module.css');
require('./components/header/Component.mobile.js');
require('@alfalab/icons-glyph/CrossMIcon');
require('./components/header/mobile.module.css');
require('./mobile.module.css');
require('./transitions.mobile.module.css');



exports.SidePanelResponsive = Component_responsive.SidePanelResponsive;
exports.ModalContext = Context.ModalContext;
