export { TooltipDesktop as Tooltip } from './Component.js';
export { TooltipResponsive } from './component.responsive.js';
import 'react';
import 'react-merge-refs';
import 'classnames';
import '../../popover/modern';
import '../../bottom-sheet/modern';
import '../../button/modern';
import '@alfalab/hooks';
import './utils.js';
