var components_primaryTablist_Component_responsive = require('./components/primary-tablist/Component.responsive.js');
var components_scrollableContainer_Component = require('./components/scrollable-container/Component.js');
var components_secondaryTablist_Component_responsive = require('./components/secondary-tablist/Component.responsive.js');
var components_tab_Component = require('./components/tab/Component.js');
var components_tabs_Component_responsive = require('./components/tabs/Component.responsive.js');
var hooks_useTabs = require('./hooks/use-tabs.js');
var hooks_useCollapsibleElements = require('./hooks/use-collapsible-elements.js');
require('./tslib.es6-0e9bf404.js');
require('react');
require('@alfalab/hooks');
require('./components/primary-tablist/Component.desktop.js');
require('./components/primary-tablist/Component.js');
require('classnames');
require('../../badge/cssm');
require('../../keyboard-focusable/cssm');
require('../../picker-button/cssm/desktop');
require('./hooks/use-tablist-titles.js');
require('@juggle/resize-observer');
require('./synthetic-events.js');
require('./components/title/Component.js');
require('compute-scroll-into-view');
require('./components/scrollable-container/index.module.css');
require('./components/primary-tablist/index.module.css');
require('./components/primary-tablist/Component.mobile.js');
require('./components/primary-tablist/mobile.module.css');
require('./components/secondary-tablist/Component.desktop.js');
require('./components/secondary-tablist/Component.js');
require('../../tag/cssm');
require('./components/secondary-tablist/index.module.css');
require('./components/secondary-tablist/Component.mobile.js');
require('./components/secondary-tablist/mobile.module.css');
require('./components/tab/index.module.css');
require('./components/tabs/Component.js');



exports.PrimaryTabListResponsive = components_primaryTablist_Component_responsive.PrimaryTabListResponsive;
exports.ScrollableContainer = components_scrollableContainer_Component.ScrollableContainer;
exports.SecondaryTabListResponsive = components_secondaryTablist_Component_responsive.SecondaryTabListResponsive;
exports.Tab = components_tab_Component.Tab;
exports.TabsResponsive = components_tabs_Component_responsive.TabsResponsive;
exports.useTabs = hooks_useTabs.useTabs;
exports.useCollapsibleElements = hooks_useCollapsibleElements.useCollapsibleElements;
