export { DateTimeInputResponsive } from './Component.responsive.js';
import 'react';
import '@alfalab/hooks';
import './components/date-time-input/Component.js';
import 'react-merge-refs';
import 'classnames';
import '../../calendar/modern';
import '../../icon-button/modern';
import '../../input/modern';
import '../../popover/modern';
import '@alfalab/icons-glyph/CalendarMIcon';
import './utils/format.js';
import 'date-fns/isValid';
import 'date-fns/parse';
import './Component.desktop.js';
import './Component.mobile.js';
