export { PrimaryTabListDesktop } from './components/primary-tablist/Component.desktop.js';
export { ScrollableContainer } from './components/scrollable-container/Component.js';
export { SecondaryTabListDesktop } from './components/secondary-tablist/Component.desktop.js';
export { Tab } from './components/tab/Component.js';
export { TabsDesktop } from './components/tabs/Component.desktop.js';
export { useTabs } from './hooks/use-tabs.js';
export { useCollapsibleElements } from './hooks/use-collapsible-elements.js';
import 'react';
import 'classnames';
import '../../badge/modern';
import '../../keyboard-focusable/modern';
import '../../picker-button/modern/desktop';
import '@alfalab/hooks';
import '@juggle/resize-observer';
import './components/title/Component.js';
import 'compute-scroll-into-view';
import './index.module-a40a00d4.js';
import '../../tag/modern';
import './index.module-8eccc1a1.js';
import './components/primary-tablist/Component.js';
import './hooks/use-tablist-titles.js';
import './synthetic-events.js';
import './components/secondary-tablist/Component.js';
import './components/tabs/Component.js';
