export { PrimaryTabListResponsive } from './components/primary-tablist/Component.responsive.js';
export { ScrollableContainer } from './components/scrollable-container/Component.js';
export { SecondaryTabListResponsive } from './components/secondary-tablist/Component.responsive.js';
export { Tab } from './components/tab/Component.js';
export { TabsResponsive } from './components/tabs/Component.responsive.js';
export { useTabs } from './hooks/use-tabs.js';
import 'react';
import '@alfalab/hooks';
import 'classnames';
import '../../badge/modern';
import '../../keyboard-focusable/modern';
import '../../picker-button/modern/desktop';
import '@juggle/resize-observer';
import './components/title/Component.js';
import 'compute-scroll-into-view';
import './index.module-a40a00d4.js';
import './components/primary-tablist/Component.mobile.js';
import '../../tag/modern';
import './index.module-8eccc1a1.js';
import './components/secondary-tablist/Component.mobile.js';
import './components/primary-tablist/Component.desktop.js';
import './components/primary-tablist/Component.js';
import './hooks/use-tablist-titles.js';
import './hooks/use-collapsible-elements.js';
import './synthetic-events.js';
import './components/secondary-tablist/Component.desktop.js';
import './components/secondary-tablist/Component.js';
import './components/tabs/Component.js';
