export { Initial } from './component.js';
import 'react';
import 'classnames';
import '../../../../../button/esm';
import '../../../../../code-input/esm';
import '../../../../../link/esm';
import '../../../../../typography/esm';
import '@alfalab/hooks';
import '../../../context.js';
import '../../header/component.js';
import '../../../countdown-section-8814b585.js';
import '../../../../../loader/esm';
import '../../../utils.js';
