import { ChangeEvent, FC, MutableRefObject, ReactNode } from 'react';
import { FormControlProps } from "../../../form-control";
import { FieldProps } from "../../../select";
import { TagComponent } from "../../types";
type TagListOwnProps = {
    value?: string;
    handleDeleteTag?: (key: string) => void;
    onInput?: (event: ChangeEvent<HTMLInputElement>) => void;
    inputRef?: MutableRefObject<HTMLInputElement>;
    autocomplete?: boolean;
    isPopoverOpen?: boolean;
    collapseTagList?: boolean;
    moveInputToNewLine?: boolean;
    transformCollapsedTagText?: (collapsedCount: number) => string;
    transformTagText?: (tagText?: ReactNode) => ReactNode;
    Tag?: TagComponent;
    handleUpdatePopover?: () => void;
};
declare const TagList: FC<FieldProps & FormControlProps & TagListOwnProps>;
export { TagList };
