export { Typography } from './component.js';
export { typographyPresets } from './presets.js';
import './text/component.js';
import './colors.module-8732cbf6.js';
import 'react';
import 'classnames';
import './title/index.js';
import './title/component.js';
import './common.module-4f616a19.js';
import './title-mobile/component.js';
import './title-responsive/component.js';
