export { Initial } from './initial/component.js';
export { Hint } from './hint/component.js';
export { FatalError } from './fatal-error/component.js';
export { TempBlock } from './temp-block/component.js';
import 'react';
import 'classnames';
import '../../../../button/modern';
import '../../../../code-input/modern';
import '../../../../link/modern';
import '../../../../typography/modern';
import '@alfalab/hooks';
import '../../context.js';
import '../header/component.js';
import '../../countdown-section-e6fd8508.js';
import '../../../../loader/modern';
import '../countdown-loader/component.js';
import '../../utils.js';
