export { CalendarInputDesktop } from './Component.desktop.js';
import './Component-c0c7ebc3.js';
import 'react';
import 'react-merge-refs';
import 'classnames';
import '../../calendar/esm';
import '../../date-input/esm';
import '../../popover/esm';
import '@alfalab/icons-glyph/CalendarMIcon';
import './utils.js';
import 'date-fns/format';
import 'date-fns/isSameDay';
import 'date-fns/parse';
