export { CalendarInputResponsive as CalendarInput } from './Component.responsive.js';
export { DATE_FORMAT, DATE_MASK, IS_BROWSER, NATIVE_DATE_FORMAT, SUPPORTS_INPUT_TYPE_DATE, formatDate, isInputDateSupported, isValidInputValue, parseDateString } from './utils.js';
import './Component-c0c7ebc3.js';
import 'react';
import 'react-merge-refs';
import 'classnames';
import '../../calendar/esm';
import '../../date-input/esm';
import '../../popover/esm';
import '@alfalab/icons-glyph/CalendarMIcon';
import '@alfalab/hooks';
import 'date-fns/format';
import 'date-fns/isSameDay';
import 'date-fns/parse';
import './Component.desktop.js';
import './Component.mobile.js';
