export { ModalResponsive } from './Component.responsive.js';
import 'react';
import '@alfalab/hooks';
import './components/closer/Component.js';
import 'classnames';
import '../../icon-button/modern';
import '@alfalab/icons-glyph/CrossHeavyMIcon';
import '../../base-modal/modern';
import './components/content/Component.js';
import './ResponsiveContext.js';
import './components/footer/Component.js';
import './components/header/Component.js';
import '@alfalab/icons-glyph/CrossMIcon';
import './Component.js';
import 'react-merge-refs';
import './Context.js';
