import 'react';
import 'classnames';
import '../../../../base-modal/esm';
import '../../../../typography/esm';
export { a as Header } from '../../component-efdd9be5.js';
import '../backer/Component.js';
import '../closer/Component.js';
import 'react-div-100vh';
import 'react-swipeable';
import '../footer/Component.js';
import '../../../../backdrop/esm';
import '../../../../icon-button/esm';
import '@alfalab/icons-glyph/ArrowBackMIcon';
import '@alfalab/icons-glyph/CrossMIcon';
import '../../tslib.es6-1d201b00.js';
import '../swipeable-backdrop/Component.js';
