export { Initial } from './screens/initial/component.js';
export { Hint } from './screens/hint/component.js';
export { FatalError } from './screens/fatal-error/component.js';
export { TempBlock } from './screens/temp-block/component.js';
export { CountdownLoader } from './countdown-loader/component.js';
import 'react';
import 'classnames';
import '../../../button/esm';
import '../../../code-input/esm';
import '../../../link/esm';
import '../../../typography/esm';
import '@alfalab/hooks';
import '../context.js';
import './header/component.js';
import '../countdown-section-8814b585.js';
import '../../../loader/esm';
import '../utils.js';
