require('../../tslib.es6-0e9bf404.js');
require('react');
require('../arrow/Component.js');
var presets_useSelectWithApply_optionsListWithApply_Component = require('../../Component-a6199ac9.js');
require('../field/Component.js');
require('../optgroup/Component.js');
require('../option/Component.js');
require('classnames');
require('@alfalab/icons-glyph/ChevronDownMIcon');
require('../arrow/index.module.css');
require('react-merge-refs');
require('downshift');
require('../../../../bottom-sheet/cssm');
require('../../../../modal/cssm/mobile');
require('../../Component.js');
require('../../Component-246be813.js');
require('@juggle/resize-observer');
require('../../../../popover/cssm');
require('@alfalab/hooks');
require('../../utils.js');
require('../native-select/Component.js');
require('../base-select/index.module.css');
require('../options-list/Component.js');
require('../../../../scrollbar/cssm');
require('../options-list/index.module.css');
require('../optgroup/index.module.css');
require('../../../../form-control/cssm');
require('../field/index.module.css');
require('../base-select-mobile/checkmark/Component.js');
require('../../../../badge/cssm');
require('@alfalab/icons-glyph/CheckmarkCircleMIcon');
require('@alfalab/icons-glyph/CheckmarkMIcon');
require('../base-select-mobile/checkmark/index.module.css');
require('../checkmark/Component.js');
require('../../../../checkbox/cssm');
require('../checkmark/index.module.css');
require('../option/index.module.css');
require('react-virtual');
require('../virtual-options-list/index.module.css');
require('../base-option/Component.js');
require('../base-checkmark/Component.js');
require('../base-checkmark/index.module.css');
require('../base-option/index.module.css');
require('../../../../skeleton/cssm');
require('../../presets/useSelectWithLoading/index.module.css');
require('../../presets/useLazyLoading/index.module.css');
require('../../intersection-observer-9ec5cf59.js');
require('../../../../button/cssm');
require('../../presets/useSelectWithApply/options-list-with-apply/index.module.css');
require('../base-select-mobile/options-list/Component.js');
require('../../../../base-modal/cssm');
require('../base-select-mobile/options-list/index.module.css');
require('../base-select-mobile/index.module.css');



exports.SelectMobile = presets_useSelectWithApply_optionsListWithApply_Component.SelectMobile;
