export { Header } from './Component.js';
import 'react';
import '../../context.js';
import '../header-info-block/Component.js';
import '../../../../typography/esm';
import '../../../../icon-button/esm';
import '../../../../tooltip/esm';
import '@alfalab/icons-glyph/ArrowsInwardMIcon';
import '@alfalab/icons-glyph/ArrowsOutwardMIcon';
import '@alfalab/icons-glyph/CrossMIcon';
import '@alfalab/icons-glyph/PointerDownMIcon';
import '../../utils/utils.js';
import '../../utils/constants.js';
import './buttons.js';
import '../../tslib.es6-748104c5.js';
import '../../utils/split-filename.js';
