import { ReactElement, ReactNode } from 'react';
import { Comment } from "../../comment";
import { Amount } from "./amount/index";
import { AmountTitle } from "./amount-title/index";
import { FooterButton } from "./footer-button/index";
import { FooterText } from "./footer-text/index";
import { Graphics } from "./graphics/index";
import { Text } from "./text/index";
type TextElement = ReactElement<typeof Text>;
type GraphicsElement = ReactElement<typeof Graphics>;
type AmountElement = ReactElement<typeof Amount>;
type AmountTitleElement = ReactElement<typeof AmountTitle>;
type CommentElement = ReactElement<typeof Comment>;
type FooterButtonElement = ReactElement<typeof FooterButton>;
type FooterTitleElement = ReactElement<typeof FooterText>;
type FooterElement = Array<ReactElement<FooterButtonElement> | FooterTitleElement> | CommentElement;
type MainElement = Array<undefined | '' | TextElement | AmountElement | AmountTitleElement> | (TextElement | AmountElement | AmountTitleElement);
type ContentElement = Array<MainElement | AddonElement | FooterElement> | MainElement;
type AddonElement = Array<TextElement | ReactNode> | TextElement | ReactNode;
type PureCellElement = Array<GraphicsElement | ContentElement> | ContentElement;
export { GraphicsElement, CommentElement, FooterElement, MainElement, ContentElement, AddonElement, PureCellElement };
