export { ImageViewer } from './component.js';
import 'react';
import 'classnames';
import 'element-closest';
import 'swiper';
import 'swiper/react';
import '@alfalab/hooks';
import '@alfalab/icons-glyph/ChevronBackHeavyMIcon';
import '@alfalab/icons-glyph/ChevronForwardHeavyMIcon';
import '../../context.js';
import '../../slide-d07efafa.js';
import '../../../../typography/modern';
import 'swiper/swiper.min.css';
import '../../utils/utils.js';
import '../../utils/constants.js';
import './paths.js';
