import 'react';
import 'classnames';
import '../../../../base-modal/modern';
import '../../../../typography/modern';
export { a as Header } from '../../component-d2ec1278.js';
import '../backer/Component.js';
import '../closer/Component.js';
import 'react-div-100vh';
import 'react-swipeable';
import '../footer/Component.js';
import '../../../../backdrop/modern';
import '../../../../icon-button/modern';
import '@alfalab/icons-glyph/ArrowBackMIcon';
import '@alfalab/icons-glyph/CrossMIcon';
import '../swipeable-backdrop/Component.js';
