export { BaseModal, BaseModalContext } from './Component.js';
export { getScrollbarSize, handleContainer, hasScrollbar, isScrolledToBottom, isScrolledToTop, restoreContainerStyles } from './utils.js';
import 'react';
import 'react-focus-lock';
import 'react-merge-refs';
import 'react-transition-group';
import '@juggle/resize-observer';
import 'classnames';
import '../../backdrop/esm';
import '../../portal/esm';
import '../../stack/esm';
import './matches-polyfill.js';
import '../../global-store/esm';
