export { Option } from './Component.js';
import 'react';
import 'classnames';
import '../base-select-mobile/checkmark/Component.js';
import '../../../../badge/esm';
import '@alfalab/icons-glyph/CheckmarkCircleMIcon';
import '@alfalab/icons-glyph/CheckmarkMIcon';
import '../checkmark/Component.js';
import '../../../../checkbox/esm';
import '../../tslib.es6-0bbcaa10.js';
