export { IntlPhoneInput } from './component.js';
import './component-064f33de.js';
import 'react';
import 'react-merge-refs';
import 'classnames';
import '@alfalab/hooks';
import '@alfalab/icons-glyph/WorldMagnifierMIcon';
import './components/flag-icon/component.js';
import '../../input-autocomplete/esm';
import '@alfalab/utils';
import './components/select/component.js';
import '../../select/esm';
import './utils/calculateCaretPos.js';
import './utils/format-phone-with-unclearable-country-code.js';
import './utils/preparePasteData.js';
import './useCaretAvoidCountryCode.js';
import './components/flag-icon/flagSprite.js';
