export { ConfirmationDesktop as Confirmation } from './component.desktop.js';
export { ConfirmationResponsive } from './component.responsive.js';
export { Initial } from './components/screens/initial/component.js';
export { Hint } from './components/screens/hint/component.js';
export { FatalError } from './components/screens/fatal-error/component.js';
export { TempBlock } from './components/screens/temp-block/component.js';
export { CountdownLoader } from './components/countdown-loader/component.js';
export { ConfirmationContext } from './context.js';
export { defaultTexts } from './types.js';
export { ONE_DAY, ONE_MINUTE, formatMsAsMinutes, useConfirmation, useCountdown } from './utils.js';
import './component-32bbfbc1.js';
import 'react';
import 'classnames';
import '@alfalab/hooks';
import '../../button/esm';
import '../../code-input/esm';
import '../../link/esm';
import '../../typography/esm';
import './components/header/component.js';
import './countdown-section-8814b585.js';
import '../../loader/esm';
import './component.mobile.js';
