export { PrimaryTabListResponsive } from './components/primary-tablist/Component.responsive.js';
export { ScrollableContainer } from './components/scrollable-container/Component.js';
export { SecondaryTabListResponsive } from './components/secondary-tablist/Component.responsive.js';
export { Tab } from './components/tab/Component.js';
export { TabsResponsive } from './components/tabs/Component.responsive.js';
export { useTabs } from './hooks/use-tabs.js';
export { useCollapsibleElements } from './hooks/use-collapsible-elements.js';
import 'react';
import '@alfalab/hooks';
import 'classnames';
import '../../badge/esm';
import '../../keyboard-focusable/esm';
import '../../picker-button/esm/desktop';
import '@juggle/resize-observer';
import './components/title/Component.js';
import 'compute-scroll-into-view';
import './index.module-898e6905.js';
import './components/primary-tablist/Component.mobile.js';
import '../../tag/esm';
import './index.module-f7eca376.js';
import './components/secondary-tablist/Component.mobile.js';
import './tslib.es6-3f4e7063.js';
import './components/primary-tablist/Component.desktop.js';
import './components/primary-tablist/Component.js';
import './hooks/use-tablist-titles.js';
import './synthetic-events.js';
import './components/secondary-tablist/Component.desktop.js';
import './components/secondary-tablist/Component.js';
import './components/tabs/Component.js';
